### PR TITLE
Fix latex sphinx's configuration (for pdf output)

### PR DESCRIPTION
**Pull request by skirpichev**
Now pdf generation should work on RTD too.  You can reproduce their pdf build with:
```
cd doc/source/
sphinx-build -b latex -d _build/doctrees . _build/latex
cd _build/latex/
pdflatex -interaction=nonstopmode main.tex 
```

See [latest build](http://mpmath.readthedocs.org/en/latest/) and [pdf output](https://readthedocs.org/projects/mpmath/downloads/pdf/latest/).

### CODE REVIEW

**Comment by skirpichev** [comment]
Ok, now this works.  See [latest build](http://mpmath.readthedocs.org/en/latest/) and [pdf output](https://readthedocs.org/projects/mpmath/downloads/pdf/latest/).

**Comment by fredrik-johansson** [comment]
Thanks.

P.S. a default sphinx makefile (make latexpdf) would be nice.

**Comment by skirpichev** [comment]
> a default sphinx makefile (make latexpdf) would be nice.

I'll think about.

BTW, now http://mpmath.readthedocs.org/ works from your repo.

Unfortunately, I can't add you as a maintainer for this documentation.  Do you have an account on RTD?

Also, this site has now only latest version of docs, i.e. from the master branch.  You could tags like it was done [here](https://github.com/skirpichev/mpmath/tags) to display different versions.

**Comment by fredrik-johansson** [comment]
I created an account on RTD (fredrikj).

**Comment by skirpichev** [comment]
Ok, now you should have access to https://readthedocs.org/projects/mpmath/

**Comment by skirpichev** [comment]
Ok, it seems now different versions of docs are displayed:
http://mpmath.readthedocs.org/en/latest/
http://mpmath.readthedocs.org/en/0.19/
http://mpmath.readthedocs.org/en/0.18/
http://mpmath.readthedocs.org/en/0.17/

**Pull request merged**
