### PR TITLE
Implement unary plus for matrices (+M == M)

### PR DESCRIPTION
**Pull request by MaxGaukler**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
For scalars, the meaning is actually slightly different: +x rounds to the current precision. This should probably be consistent for matrices.

**Comment by MaxGaukler** [comment]
fixed that.

**Comment by MaxGaukler** [comment]
If there is anything missing to get this merged, please let me know.

**Comment by fredrik-johansson** [comment]
No, this is indeed fine. Thanks!

**Pull request merged**
