### PR TITLE
Optimized python_trailing function

### PR DESCRIPTION
**Pull request by adhoc-king**
Included a look-up table which reduces time by 50% for numbers which have a non-zero bit in the lowest byte

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Wow, nice find! I can't believe I overlooked such a crucial optimization when writing this code.

Could you make a few further improvements?

To precompute the table, the following is 140 times faster:

    small_trailing = [0] * 256
    for j in range(1,8):
        small_trailing[1<<j::1<<(j+1)] = [j] * (1<<(7-j))

In the fallback loop, instead of taking 1 bit at a time, the loop could mask out 8 bits at a time until the lookup table can be used.

Actually, this is still an O(n^2) algorithm for powers of two which isn't really ideal. I wonder if using hex() in the fallback case would be better?

**Comment by fredrik-johansson** [comment]
Yes, exactly. (Perhaps a micro-optimization you could also start with t = 8, n >>= 8 since the first loop iteration always succeeds.)

It's O(n^2) because each n >>= 8 operation is O(n) (relevant only for huge numbers).

**Comment by fredrik-johansson** [comment]
Of course, O(n) and O(n^2) should be O(log(n)) and O(log(n)^2) above.

**Comment by adhoc-king** [comment]
Made a pull request #430 
Thanks a lot! I learnt many things :)

**Pull request closed without merging**
