### PR TITLE
Use codecov.io for code coverage reports in Travis

### PR DESCRIPTION
**Pull request by skirpichev**
Here is [my repo](https://github.com/skirpichev/omg) as an example that uses [this tool](https://codecov.io/).

Some key features
* Codecov badge in README.rst has a link to complete coverage reports.  With their browser plugin you can see this statistics in the github interface too.
* For pull requests you could enable codecov checks ("project" - for the project as whole and "patch" - to measure patch coverage).

### CODE REVIEW

**Comment by skirpichev** [comment]
Apparently, coveragepy doesn't support python 3.2.  Maybe it worth dropping old python releases (3.2 and, perhaps, 2.6 too) from the supported list?

**Comment by fredrik-johansson** [comment]
> Maybe it worth dropping old python releases (3.2 and, perhaps, 2.6 too) from the supported list?

That's fine with me.

**Comment by skirpichev** [comment]
Ok, 2.6 and 3.2 now removed from travis build matrix.

What about pr itself?  Does this make sense for you?

**Comment by fredrik-johansson** [comment]
It still says "2.6 or later". Otherwise, sure, test coverage reports are useful, I don't see this causing any harm.

**Comment by skirpichev** [comment]
> It still says "2.6 or later".

Indeed, sorry.  Now this patch is more conservative and I removed 3.2 tests only.

> Otherwise, sure, test coverage reports are useful, I don't see this causing any harm.

Ok, then you can try to enable coverage for this project in codecov.io.  It may require lowering some limits to pass tests (coverage is around 80%, not too high).

**Comment by fredrik-johansson** [comment]
It looks like doctests are not included. For example mpmath.functions.qfunctions.qhyper is not covered by runtests, but does have doctests.

**Comment by skirpichev** [comment]
It seems, these doctests aren't collected at all:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/115549833/log.txt (this is in the master)

Probably, it's because of decorators AND pytest bug somewhere.  Does work with plain doctest module:
```
$ python
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import doctest
>>> doctest.testfile("mpmath/functions/qfunctions.py")
TestResults(failed=0, attempted=39)
```

But:
$ py.test --doctest-modules mpmath/functions/qfunctions.py
============================= test session starts =============================
platform linux -- Python 3.4.2, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/sk/src/mpmath, inifile: setup.cfg
plugins: cov-2.2.0
collected 0 items 

========================= no tests ran in 0.07 seconds ==========================
```

PS: codecov-io's comments could be annoying (and you may turn them off if you wish).

**Comment by fredrik-johansson** [comment]
Can you see a way to fix the doctest issue? That would be great.

How do you turn the comments off?

**Comment by skirpichev** [comment]
> Can you see a way to fix the doctest issue?

I'll look into it.  

> How do you turn the comments off?

I don't remember exactly.  I think, it's the tab "Pull request comments" in the project settings.  On my project I have all options here set to Off (i.e. "Header", "Interactive Graph" and so on).

**Comment by skirpichev** [comment]
Oh, sorry.  It looks like now it's a wrong project to contribute for me:
https://github.com/asmeurer/sympy-paper/issues/5#issuecomment-197399858
Collaborator

**Comment by fredrik-johansson** [comment]
You are of course free to choose what projects to contribute to. For what it's worth, I don't know anything about the conflict between you and SymPy, and I don't want to be involved in it. Personally, I have no issues whatsoever with the other SymPy developers, so as it stands, I'm happy to collaborate with them. If that's a problem for you, that's of course unfortunate. If you decide to submit patches to mpmath in the future anyway, I will review them for their technical merits, as I have in the past.

**Comment by skirpichev** [comment]
> For what it's worth, I don't know anything about the conflict between you and SymPy, and I don't want to be involved in it.

Sure.  Bad news for me, in that sense that you support their idea of banning everything they don't like to hear (aka Code of Conduct).  I have good lesson when I invested a moderate amount of my time and skills in such "open source" project to be considered as nothing in the end.

> I will review them for their technical merits, as I have in the past.

Perhaps, but I can't be sure, as you don't see anything wrong with their policy.

Sorry for this noise (i.e. PR) and thank you for your time.

**Pull request closed without merging**
