### PR TITLE
fixing issue: Determinant function raises TypeError on simple matrix #542

### PR DESCRIPTION
**Pull request by sonntagsgesicht**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
The solution looks like a bit of a hack, and it's problematic that it doesn't account for the scaling of the matrix. For example, it will return 0 if you input the identity matrix times 1e-30. It would be fine if you check any column for being exactly zero, but perhaps that isn't general enough.

**Comment by sonntagsgesicht** [comment]
Yes, you are right. Had a closer look and fixed it directly inside LU_comp where pivoting failed. 
Added a LU_comp, too. But, since I have no `pytest` experience on testing exceptions, this test looks more like a hack, too.

**Comment by mgmax** [comment]
If you don't like the compact `pytest.raises(Exception, function)` notation, you can also use `pytest.raises` like this:
```
    with pytest.raises(MyException):
        do_something_wrong()
```
This checks that the expected exception is thrown somewhere within the "with"-block, and is actually the recommended notation in the [pytest docs](https://docs.pytest.org/en/latest/reference.html#pytest-raises).

**Comment by vks** [comment]
The updated fix looks good to me.

**Review by vks — APPROVED** [review]

**Pull request closed without merging**
