### PR TITLE
Fixed scalar-matrix multiplication in iv module

### PR DESCRIPTION
**Pull request by warnerjon12**

### CODE REVIEW

**Comment by warnerjon12** [comment]
I had accidentally rebased one commit too far, so the history shows an extra commit. I am not sure how to remove me from that while keeping the commit, would be nice to know.

**Comment by fredrik-johansson** [comment]
Seems ok.

**Comment by fredrik-johansson** [comment]
Reverted because of failing tests. I don't get why -- this PR was green before the merge.

**Comment by warnerjon12** [comment]
I will have to look at that when I have more time

**Pull request merged**
