### PR TITLE
Added the signal functions: square wave, triangle wave, sawtooth wave, and logistic sigmoid in signals.py and Sphinx documentation code in signals.txt

### PR DESCRIPTION
**Pull request by ndattani**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Sorry about the delay. Could you rebase this and squash the commits?

Quick comments:

* The new functions should make sure that inputs get converted to the right type. You can use @defun_wrapped for this.
* return 0 should be return ctx.zero
* Maybe rename sigmoidw -> sigmoid?

**Comment by ndattani** [comment]
Thanks @fredrik-johansson! Do you want us to squash the ~20 commits into just 1 commit, or perhaps squash it down to 3 commits: one for the contributions by myself (@ndattani), one for the contributions of Tina (@t98yu), and one for the contributions of Deyan (@deyanmihaylov) ?

**Comment by fredrik-johansson** [comment]
Either 1 or 3 commits is fine :-)

Don't forget the type conversions.

**Comment by ndattani** [comment]
> Either 1 or 3 commits is fine :-)
> 
> Don't forget the type conversions.

@fredrik-johansson  The 21 commits are now squashed down to 3 commits (1 for each author). The type conversions are now done :) Please see Pull Request #640. I’ll close this one since we did the squashed version in a different branch!

**Pull request closed without merging**
