### PR TITLE
Return passed in function in defun* decorators

### PR DESCRIPTION
**Pull request by skirpichev**
This turn on more doctests, e.g.:

```
$ py.test mpmath/functions/qfunctions.py
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/sk/src/mpmath/.hypothesis/examples')
rootdir: /home/sk/src/mpmath, inifile: setup.cfg
plugins: xdist-1.26.1, timeout-1.3.3, forked-1.0.1, cov-2.6.1, hypothesis-4.4.3
collected 4 items

mpmath/functions/qfunctions.py ....                                      [100%]

=========================== 4 passed in 0.49 seconds ===========================
```

### CODE REVIEW

**Comment by skirpichev** [comment]
There are couple of doctests to be fixed.

**Comment by fredrik-johansson** [comment]
Are you fixing the doctests? Looks like simple things:
* missing () in print
* NoConvergence -> mpmath.libmp.libhyper.NoConvergence
* (1.0000000000000007+0j) -- if not consistent, could change print() to nprint()
* (0.023104993115419 - 9.94965213042341e-35j) -- chop() this

**Comment by skirpichev** [comment]
Ok, doctests were adapted, please review.  If this is OK, I'll rebase PR.

I noticed random failures of "pip install" for py3.4 (e.g. [this build](https://travis-ci.org/fredrik-johansson/mpmath/builds/488148785).  End of life for this version coming soon, so I'm not sure if I should waste time on debugging this problem, hence build job for 3.4 was removed.  If you agree, I'll also adapt documentation.

**Comment by fredrik-johansson** [comment]
Fine with me.

**Comment by skirpichev** [comment]
Where it's expected to be covered, which test/doctest?

**Comment by skirpichev** [comment]
Oh, it seems, you have more broken defun decorators...

**Pull request merged**
